server:
  port: 8000
spring:
  application:
    name: wangff
  datasource:
    primary:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/db1?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: wj370307
    secondary:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/db2?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: wj370307

mybatis:
  type-aliases-package: com.wdcloud.wangff.model
  mapper-locations: classpath:mapper/**.xml