server:
  port: 8000
spring:
  application:
    name: wangff
  datasource:
    druid:
        url: jdbc:mysql://192.168.9.240:3306/activity?useUnicode=true&characterEncoding=utf-8
        username: activity
        password: activity_dazb
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialSize: 1
        maxActive: 20
        minIdle: 1
        maxWait: 60000
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        validationQuery: select 1
        validation-query-timeout: 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        timeBetweenEvictionRunsMillis: 10000
        minEvictableIdleTimeMillis: 30001
        async-close-connection-enable: true
        filters: stat
        removeAbandoned: true
        removeAbandonedTimeout: 300
        logAbandoned: true
